STANDARD_USER = "standard_user"
PROBLEM_USER = "problem_user"
PERFORMANCE_GLITCH_USER = "performance_glitch_user"
STANDARD_PASSWORD = "secret_sauce"
INVALID_PASSWORD = "wrong_password"
INVALID_USER = "fake_user"
LOCKED_OUT_USER = "locked_out_user"